#+TITLE: traceroute

* Introduction
除了ping之外，traceroute应该是作为流行的网络诊断工具了;这个工具主要用来“显示IP packets的路由信息”和“衡量IP packets的时延情况”。
根据man手册，traceroute最开始是Van Jacobson在1987年开发的；后来广泛移植到各大平台（mac、Linux、WinNT等）；其中WinNT系统上名称叫tracert。


* 用ping探索路由
其实ping存在-R选项，可以在IP包的option段内存放路由信息，但是存在诸多原因，这一特性并没有被广泛的应用；比如：
- 比如历史原因，并非所有的router支持-R选项
- 最重要的是，IP包格式限制了option字段最大有37bytes，也就是最多存放9条路由；它的空间限制了这个特性的应用。

相比ping，traceroute提供了更全面的路由探测机制。


* The Theory of tranceroute[fn:1]
在传统的*nix系统，traceroute默认发送一系列的UDP报文来实现路由探测；这些UDP报文的目的端口号往往选择目的主机不可能使用的端口号（一般大于30000）。
在探测的过程中，traceroute利用ICMP报文、TTL来进行控制进度；通过不断增大TTL，根据返回的TCMP报文是“time exceed”或者“port unreachable”来判断是否继续。

TTL（Time to live）是IP包中一个8bit的区域，IP包的发送方负责初始化这个值。RFC建议应用程序大部分情况下应该设置为64；任何一个IP packet流经某一个router时必须将TTL减1。
如果路由器收到的IP包的TTL为0或者1，则不会对该报文进行转发；相反的，路由器应该丢弃它并给源主机发送“time exceed” ICMP报文。

现在我们可以描述traceroute的工作流程：
1. 首先traceroute发送TTL=1的报文，经过第一个路由器器时，路由器将TTL减1，并丢弃；给源主机发送time exceed icmp报文；
2. traceroute记录下第一跳的地址并打印；接着发送TTL=2的报文，经过第二个路由器的时候，路由器将TTL减1并丢弃，给源主机发送time exceed 报文。
3. …… 如此，知道traceroute发送的TTL=N报文到达目的主机，目的主机当前没有监听相应端口的UDP服务，返回port unreachable报文；
4. traceroute打印最后一跳（目的主机），结束运行。

* some key point
** 协议
在*nix平台，traceroute默认使用UDP作为探测报文；而WinNTtracert默认使用ICMP作为探测报文。不过traceroute程序支持-I选项标识使用icmp echo作为探测报文，或者-P选项指定任何协议（UDP、TCP等）。
** 时延计算
traceroute发送探测包前会将发送时间保存至本地，当对用的包返回后，用当前事件减去保存的发送时间得出RTT延时。
** 路径保证
1. 由于互联网本质是一个“分组交换”系统，不能保证不同的包走的是完全相同的路径（虽然往往经常如此）；有些情况下会发现traceroute的数据中存在相同的hop。
2. traceroute期望发出的包在指定的时间内（server seconds）返回；如果没有在指定的时间内返回，traceroute利用“星号”来代替返回值，并继续进行下一跳检测。(往往星号的愿意是经过的路由器通过iptables做了策略，禁止icmp time exceed包回传)

* traceroute的注意点[fn:2]
1. traceroute打印的IP紧紧代表经过的网卡接口IP，不能代表路由器的IP。
2. 如上所说，如果router不相应traceroute或者限制icmp响应的回传，则traceroute不能探测到该路由器。
3. 网络部署环境设备多样（防火墙、网管、路由load blance），有些traceroute变体有一定的优势：比如tcptraceroute、layer four traceroute、Paris-traceroute等。



* Footnotes

[fn:1] Tcp/ip illustrated: Volume 1

[fn:2] https://en.wikipedia.org/wiki/Traceroute
