#+TITLE:观念的成长
#+STARTUP:showall
#+DATE: 20180204

* preface
个人经验学识的不断积累，让我们在当前观念体系中实现成长和不断磨练。基于这些“量”的
变化，自身也在发生了一些变化；总有一天会发现当前的观念已经不能驾驭你目前的所得了，
于是“质”发生了变化，这是“观念的成长”。

* 缘由
最近在开展一个与 kernel 相关的项目，按照之前的成长环境和观念，kernel 方向是很复
杂而且很困难的方向，换句话说不是一般人能够驾驭的了的。我就在想，我可以成为“这个
非一般人”吗。随着近一个月的调研工作，我逐渐感觉自己可以把控这个方向可以胜任——“其
实kernel 也没有想象的那么困难”。

由这件事情，产生了开头所说的“观念的成长”——一开始认为我无法把控 kernel 相关项目，
现在变为我可以把控 kernel相关项目。

* 引经据典
回想之前，很多不可能的事情，经由外界的压力或者其他原因，我们做到了。但是即使做到
之后，我们总是心有余悸，似乎这不是自己能完成的；大部分原因是个人观念还没有得到对
应的成长，从而产生了不自信。这个时候需要我们主动探索，调整自己，适应“新的自己”。


打个比方：《龙珠》动画片中，孙悟空和克林第一次跟着龟仙人学武功，其实就是做了很多
力量型锻炼，然后就去参加第一次武术大会。但是就发现自己的能力已经远远超过了几乎所
有选手，以至于自己都不敢相信；后来悟空发现这个现象，告诉克林不能使用“全力”（不然
克林的师兄可能就被克林打死了）。

* 问题来了
既然是这样，提出几个问题：
1. 如何让自己更快的得到"观念的成长"？
2. 如何发现自己当前的观念已经不适合当前的自己，从而实现尽快的调整呢？

先说一下我的思考：
第一个问题，“观念的成长”是本质的成长，决定了个人对世界、对自己
的认知；认知不对，就很难做出争取的决定。但是“观念的成长”脱离不开“现实生活”，我们
依然需要不断的实际工作、实际项目、交友、阅读或者写作等各类生活活动，只有个人能力、
境界具备“观念成长”的土壤，“观念成长”才会可能出现在你的生活。
- 如果你当前已经具备要成长的某一观念的条件，主动自省、多思考、多读书、多与人探讨，
  或许下一秒就是你“拈花一笑”的时刻。
- 如果当前你还没有具备“土壤”，那就多多参与社会劳动，体悟、总结生活，同样也需要多
  思考、多留个心眼。

第二个问题，本质上如何“认识自我”。在对自己有一定的认识基础上，遇到生活中的事情后，
无论当时是如何处理的，事后时常总结；这个过程也是不断加深“自我认知”的过程。当发现
某个观念不适合当前的自己、甚至影响了个人成长时，那就是需要调整的时刻了。

* 附注
我不清楚人为何活着，总有一天我们、他们、世界都会不复存在。但是现在我能感受到真实
的自己，或许内心想不负此生吧。
